model_id = "Vontra/GLM-5.3-Flash-MLX-oQ2-MTP"
n_layers = 45
hidden_size = 4096
supports_tensor = false
num_key_value_heads = 64
tasks = ["TextGeneration"]
family = ""
quantization = ""
base_model = ""
capabilities = []
context_length = 1048576
uses_cfg = false
trust_remote_code = false

[storage_size]
in_bytes = 110128198215

[vision]
image_token_id = 154854
model_type = "glm5_next"
weights_repo = "Vontra/GLM-5.3-Flash-MLX-oQ2-MTP"

[sampling_defaults]
